/*
CREATE TABLE sib_2018 AS

SELECT *
FROM sib_inativos
WHERE (date("DT_ULTIMO_CANCELAMENTO" || '-01') > '2018-01-01' OR "DT_ULTIMO_CANCELAMENTO" IS NOT NULL)
AND date("DT_INCLUSAO" || '-01') < '2018-12-31'
;
*/

/*
SELECT *
FROM sib_inativos
WHERE "DT_ULTIMO_CANCELAMENTO" = ""
LIMIT 1
;
*/

DELETE FROM sib_inativos
WHERE date("DT_ULTIMO_CANCELAMENTO" || '-01') < '2018-01-01'
AND "DT_ULTIMO_CANCELAMENTO" IS NOT NULL
AND "DT_ULTIMO_CANCELAMENTO" != ''
;